-- Seed: categorias do Boteco do Zé
INSERT INTO categories (id, name, short_description, sort_order) VALUES
('cervejas', 'Cervejas', 'Garrafa, long neck e chopp', 0),
('sem-alcool', 'Bebidas sem álcool', 'Opções para refrescar', 1),
('drinks', 'Caipirinhas e drinks', 'Clássicos do balcão', 2),
('copao', 'Copão', 'Whisky com energético', 3),
('doses', 'Doses', 'Servidas na medida', 4),
('doces', 'Doces e balas', 'Pra fechar a conta', 5),
('cigarros', 'Cigarros', 'Venda por unidade', 6),
('porcoes', 'Porções', 'Para dividir na mesa', 7),
('jogos', 'Jogos', 'Diversão no salão', 8);

-- Seed: 52 produtos do Boteco do Zé
INSERT INTO products (id, slug, category_id, name, price_in_cents, image_url, image_fit, image_position, image_scale, available, sort_order) VALUES
('prd_001', 'heineken', 'cervejas', 'Heineken', 1200, '/images/cervejas/Heineken Latão.jfif', 'contain', '28% 52%', NULL, 1, 0),
('prd_002', 'antarctica', 'cervejas', 'Antarctica', 800, '/images/cervejas/Antarctica Latão .png', 'contain', '28% 55%', NULL, 1, 1),
('prd_003', 'brahma', 'cervejas', 'Brahma', 800, '/images/cervejas/Brahma Latão.png', 'contain', '28% 54%', NULL, 1, 2),
('prd_004', 'amstel', 'cervejas', 'Amstel', 900, '/images/cervejas/Amstel Latão .jfif', 'contain', '28% 54%', NULL, 1, 3),
('prd_005', 'chopp-stengel', 'cervejas', 'Chopp Stengel', 1800, '/images/cervejas/Chopp Stempel.png', 'cover', '50% 50%', NULL, 1, 4),
('prd_006', 'cerveja-piriguete', 'cervejas', 'Cerveja Piriguete', 600, '/images/cervejas/Cerveja Piriguete.png', 'contain', '28% 54%', NULL, 1, 5),
('prd_007', 'long-neck-heineken', 'cervejas', 'Long Neck Heineken', 1200, '/images/cervejas/Long Neck Heineken.jfif', 'contain', '27% 51%', NULL, 1, 6),
('prd_008', 'long-neck-budweiser', 'cervejas', 'Long Neck Budweiser', 1200, '/images/cervejas/Long Neck Budweiser.jfif', 'contain', '28% 52%', NULL, 1, 7),
('prd_009', 'refrigerante', 'sem-alcool', 'Refrigerante', 1400, '/images/sem-alcool/Refrigerante 2 litros.png', 'contain', '29% 55%', NULL, 1, 8),
('prd_010', 'agua', 'sem-alcool', 'Água', 400, '/images/sem-alcool/Água.jfif', 'contain', '28% 58%', NULL, 1, 9),
('prd_011', 'start', 'sem-alcool', 'Start', 1900, '/images/sem-alcool/start energético.png', 'contain', '29% 54%', NULL, 1, 10),
('prd_012', 'refrigerante-lata', 'sem-alcool', 'Refrigerante lata', 800, '/images/sem-alcool/Refrigerante lata.jfif', 'cover', '48% 50%', NULL, 1, 11),
('prd_039', 'h2o', 'sem-alcool', 'H2O', 800, '/images/sem-alcool/H20.jpg', 'contain', '28% 50%', NULL, 1, 12),
('prd_040', 'agua-com-gas', 'sem-alcool', 'Água com gás', 400, '/images/sem-alcool/Água com gás.png', 'contain', '28% 52%', NULL, 1, 13),
('prd_043', 'guaravita', 'sem-alcool', 'Guaravita', 400, '/images/sem-alcool/Guaravita.png', 'contain', '28% 52%', NULL, 1, 14),
('prd_044', 'agua-de-coco', 'sem-alcool', 'Água de coco', 600, '/images/sem-alcool/Água de coco.png', 'contain', '28% 52%', NULL, 1, 15),
('prd_045', 'suco-del-valle', 'sem-alcool', 'Suco Del Valle', 500, '/images/sem-alcool/Suco Del Valle.png', 'contain', '28% 52%', NULL, 1, 16),
('prd_013', 'caipirinha', 'drinks', 'Caipirinha', 1600, '/images/drinks/Caipirinha.jfif', 'cover', '45% 68%', NULL, 1, 17),
('prd_014', 'caipivodka', 'drinks', 'Caipivodka', 1800, '/images/drinks/Caipivodka.jfif', 'cover', '42% 67%', NULL, 1, 18),
('prd_015', 'copao', 'drinks', 'Copão', 3000, '/images/drinks/Copão.png', 'cover', '50% 65%', NULL, 1, 19),
('prd_016', 'gin-com-tonica', 'drinks', 'Gin com Tônica', 2500, '/images/drinks/Gin com Tônica.jpg', 'cover', '46% 65%', NULL, 1, 20),
('prd_036', 'ice-off', 'drinks', 'Ice Off', 700, '/images/drinks/Ice Off.jpg', 'contain', '21% 50%', 0.85, 1, 21),
('prd_037', 'skoll-beats', 'drinks', 'Skoll Beats', 1000, '/images/drinks/Skoll Beats.webp', 'contain', '28% 52%', NULL, 1, 22),
('prd_038', 'we-mix', 'drinks', 'We Mix', 1000, '/images/drinks/We mix.jpg', 'contain', '28% 52%', NULL, 1, 23),
('prd_050', 'copao-whisky-red-label', 'copao', 'Copão de Whisky Red Label com energético', 4000, '/images/copao/copao-red-label.webp', 'cover', '50% 80%', NULL, 1, 24),
('prd_051', 'copao-whisky-cavalo-branco', 'copao', 'Copão de Whisky Cavalo Branco com energético', 3000, '/images/copao/copao-cavalo-branco.webp', 'cover', '50% 80%', NULL, 1, 25),
('prd_052', 'copao-whisky-ballantines', 'copao', 'Copão de Whisky Ballantine''s com energético', 3500, '/images/copao/copao-ballantines.webp', 'cover', '50% 80%', NULL, 1, 26),
('prd_017', 'dose-gin', 'doses', 'Gin', 600, '/images/doses/Gin.jpg', 'cover', '42% 51%', NULL, 1, 27),
('prd_018', 'campari', 'doses', 'Campari', 1200, '/images/doses/campari.jpg', 'cover', '44% 42%', NULL, 1, 28),
('prd_019', 'black-fire', 'doses', 'Black Fire', 700, '/images/doses/Black Fire.png', 'contain', '28% 53%', NULL, 1, 29),
('prd_020', 'cachaca', 'doses', 'Cachaça', 400, '/images/doses/Cachaça.png', 'contain', '28% 52%', NULL, 1, 30),
('prd_021', 'paratudo', 'doses', 'Paratudo', 400, '/images/doses/Paratudo.png', 'contain', '28% 52%', NULL, 1, 31),
('prd_022', 'cachaca-51', 'doses', 'Cachaça 51', 600, '/images/doses/Cachaça 51.png', 'contain', '28% 53%', NULL, 1, 32),
('prd_023', 'vodka', 'doses', 'Vodka', 1400, '/images/doses/Vodka.jpg', 'cover', '40% 43%', NULL, 1, 33),
('prd_024', 'canelinha', 'doses', 'Canelinha', 600, '/images/doses/Canelinha.png', 'contain', '28% 53%', NULL, 1, 34),
('prd_025', 'bananinha', 'doses', 'Bananinha', 600, '/images/doses/Bananinha.png', 'contain', '28% 53%', NULL, 1, 35),
('prd_041', 'dose-whisky-ballantines', 'doses', 'Dose de Whisky Ballantine''s', 1200, '/images/doses/Whisky Ballantines.webp', 'cover', '48% 55%', NULL, 1, 36),
('prd_042', 'dose-dreher', 'doses', 'Dose Dreher', 600, '/images/doses/Dreher.webp', 'cover', '48% 51%', NULL, 1, 37),
('prd_046', 'dose-whisky-red-label', 'doses', 'Dose de Whisky Red Label', 2000, '/images/doses/Whisky Red Label.webp', 'cover', '28% 50%', NULL, 1, 38),
('prd_047', 'dose-whisky-cavalo-branco', 'doses', 'Dose de Whisky Cavalo Branco', 1700, '/images/doses/Whisky Cavalo Branco.webp', 'cover', '28% 70%', NULL, 1, 39),
('prd_048', 'dose-vodka-smirnoff', 'doses', 'Dose de Vodka Smirnoff', 1200, '/images/doses/Vodka Smirnoff.webp', 'cover', '28% 50%', NULL, 1, 40),
('prd_026', 'bala-halls', 'doces', 'Bala Halls', 400, '/images/doces/Bala Halls.png', 'cover', '48% 60%', NULL, 1, 41),
('prd_027', 'trident', 'doces', 'Trident', 500, '/images/doces/Trident.png', 'cover', '50% 54%', NULL, 1, 42),
('prd_049', 'salgadinho', 'doces', 'Salgadinho', 400, '/images/doces/Fandangos.webp', 'cover', '48% 60%', NULL, 1, 43),
('prd_028', 'cigarro-varejo', 'cigarros', 'Cigarro Varejo', 150, '/images/cigarros/Cigarro Varejo.jpg', 'cover', '48% 54%', NULL, 1, 44),
('prd_029', 'cigarro-de-sabor', 'cigarros', 'Cigarro de Sabor', 200, '/images/cigarros/Cigarro de Sabor.jpg', 'cover', '54% 52%', NULL, 1, 45),
('prd_030', 'batata', 'porcoes', 'Batata', 2700, '/images/porçoes/Batata .jpg', 'cover', '48% 58%', NULL, 1, 46),
('prd_031', 'calabresa-acebolada', 'porcoes', 'Calabresa Acebolada', 3000, '/images/porçoes/Calabresa Acebolada .png', 'cover', '50% 53%', NULL, 1, 47),
('prd_032', 'batata-calabresa-cebola', 'porcoes', 'Batata, Calabresa e Cebola', 4500, '/images/porçoes/Batata, Calabresa e Cebola.png', 'cover', '52% 56%', NULL, 1, 48),
('prd_033', 'batata-porco-acebolado', 'porcoes', 'Batata e Porco Acebolado', 5500, '/images/porçoes/Batata e Porco Acebolado.png', 'cover', '50% 56%', NULL, 1, 49),
('prd_034', 'sinuca', 'jogos', 'Sinuca', 200, '/images/jogos/Sinuca .png', 'cover', '68% 62%', NULL, 1, 50),
('prd_035', 'fliperama', 'jogos', 'Fliperama', 200, '/images/jogos/Fliperama .png', 'cover', '27% 52%', NULL, 1, 51);
